ALLOWED_TYPES = [ 'date', 'time', 'datetime' ]
PICKER_HEIGHT = 225
PICKER_WIDTHS =
  datetime: 305
  date: 250
  time: 75

MAX_BLOCKS = 35

SELECTOR_OPTION_HEIGHT = 25


module.exports = { ALLOWED_TYPES, PICKER_HEIGHT, PICKER_WIDTHS, SELECTOR_OPTION_HEIGHT, MAX_BLOCKS }